### ISSUE TITLE
trouble deploying on vercel

### ISSUE THREAD

**Issue by Crazymoviestv** [avalos010/sportsbook-odds-comparer#3]
having issue deploying to vercel. 

⨯ ESLint: Invalid Options: - Unknown options: useEslintrc, extensions - 'extensions' has been removed.
   Collecting page data ...
   Generating static pages (0/7) ...
   Generating static pages (1/7) 
   Generating static pages (3/7) 
   Generating static pages (5/7) 
TypeError: e.map is not a function
    at l (/vercel/path0/.next/server/chunks/933.js:1:10112)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  digest: '1561288829'
}
TypeError: e.map is not a function
    at l (/vercel/path0/.next/server/chunks/933.js:1:10112)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  digest: '1561288829'
}
TypeError: e.map is not a function
    at l (/vercel/path0/.next/server/chunks/933.js:1:10112)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  digest: '1561288829'
}

**Comment by avalos010** [comment]
The issue was basically the amount of requests we get a month is 500 (free tier)  If I see we keep passing that threshold I will have to up the requests to prevent that from happening again. It fixed itself because every month the requests reset.
